server:
  port: 8081

person:
  lastName: hello
  age: ${random.int[1,100]}
  boss: false
  birth: 2017/12/12
  maps: { k1: v1,k2: 12 }
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12
spring:
  profiles:
    active: dev #开发环境   #指定配置环境
  redis:
    host: localhost
    port: 6379
    database: 0   #默认提供16个数据库，选择操作 0号数据库
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-idle: 4   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: -1ms  #最大连接阻塞等待时间
    #password: 123456  设置密码
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: groupB
  consumer:
    group: groupA
    topic: ReminderTopic

---
server:
  port: 8082
spring:
  profiles: test  #测试环境

---
server:
  port: 8083
spring:
  profiles: prod #生产环境


